# Generated by Django 4.1.3 on 2023-05-14 16:19

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoundingBoxes',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('camera_id', models.CharField(max_length=100)),
                ('boxes', models.TextField()),
            ],
        ),
    ]
