# Generated by Django 4.1.3 on 2023-05-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundingboxes',
            name='bounding_boxes',
            field=models.CharField(max_length=10000),
        ),
    ]
