# Generated by Django 4.1.3 on 2023-05-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boxes',
            new_name='BoundingBoxes',
        ),
    ]
