# Generated by Django 4.1.3 on 2023-05-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_boundingboxes_bounding_boxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundingboxes',
            name='bounding_boxes',
            field=models.TextField(),
        ),
    ]
