# Generated by Django 4.1.3 on 2023-05-14 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_boundingboxes_bounding_boxes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boundingboxes',
            old_name='bounding_boxes',
            new_name='boxes',
        ),
    ]
